### ISSUE TITLE
CUDA not found

### ISSUE THREAD

**Issue by jlb1504** [liltom-eth/llama2-webui#1]
Hey, this is really great, and I have got it working.  I have a gaming laptop with 2 GPUs: an AMD with 512 MB VRAM, and a RTX 4080 with 12 GB VRAM.  The model is running pretty well, but it is hitting the AMD, not the RTX.  When launched, I am getting "CUDA not found".  I am doing all this on Win11/WSL2.  I think I have cuda installed and enabled properly for python in WSL:

> >>> torch.cuda.is_available()
> True
> 

Here is my .env:

> MODEL_PATH = "TheBloke/Llama-2-7b-Chat-GPTQ"
> LOAD_IN_8BIT = False
> LOAD_IN_4BIT = True
> LLAMA_CPP = False
> 
> MAX_MAX_NEW_TOKENS = 2048
> DEFAULT_MAX_NEW_TOKENS = 1024
> MAX_INPUT_TOKEN_LENGTH = 4000

(Note: I had to tweak MODEL_PATH from example - this value above worked for me.  I also removed DEFAULT_SYSTEM_PROMPT for now, because it was crashing the app with "everett.ConfigurationError: Env file line missing = operator")

Do you have any suggestions on what I might need to do to get the app to recognize and use the RTX?  Thanks!

**Comment by jlb1504** [comment]
It does seem like it briefly hits the RTX.  I am pretty new to a lot of this stuff, so I may not understand what I am looking at.

![image](https://github.com/liltom-eth/llama2-webui/assets/8078266/92d46d32-b1a3-47d3-9e30-06af34375d23)

**Comment by liltom-eth** [comment]
@jlb1504 Thanks for the issue. That must be a bug [here](https://github.com/liltom-eth/llama2-webui/blob/18707217da847990e5b3220d3ba41a94c1627ce5/app.py#L69C9-L69C9). `not` should not be in that line.
That's my fault.

**Comment by liltom-eth** [comment]
Bug should be fixed with the newest commits now.

**Comment by jlb1504** [comment]
ok, so it was/is using cuda - it was just printing out the opposite.  I now see this message on launch: "Running on GPU with torch transformers."  Thanks!

**Comment by liltom-eth** [comment]
@jlb1504 Thanks for contributing, leave your Twitter name here if you like to be mentioned in some posts later.

**Comment by liltom-eth** [comment]
@jlb1504 welcome contributing your benchmark performance [here](https://github.com/liltom-eth/llama2-webui#benchmark).
