### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError on CPU

### ISSUE THREAD

**Issue by blackhawkee** [liltom-eth/llama2-webui#11]
When running the 4bit model on CPU, receiving the below error

    raise HFValidationError(huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/model/q4/llama-2-7b-chat.ggmlv3.q4_0.bin'. Use `repo_type` argument if needed.

**Comment by liltom-eth** [comment]
Try modifying your model path in `.env`.

**Comment by liltom-eth** [comment]
Do you mind listing more specific details of your env?

**Comment by smithlai** [comment]
Hi, I got the same error:

```python
HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/mnt/d/WorkTable/Projects/Temp/llama2/llama2-webui/models/Llama-2-7B-GGML/llama-2-7b.ggmlv3.q8_0.bin'. Use `repo_type` argument if needed.
```
And here's my env:
```python
MODEL_PATH = "/mnt/d/WorkTable/Projects/Temp/llama2/llama2-webui/models/Llama-2-7B-GGML/llama-2-7b.ggmlv3.q8_0.bin"
LOAD_IN_8BIT = True
LOAD_IN_4BIT = False
LLAMA_CPP = False
```

However, if I change nothing but set LLAMA_CPP to True, it works on CPU
```sh
Running on CPU with llama.cpp.
llama.cpp: loading model from /mnt/d/WorkTable/Projects/Temp/llama2/llama2-webui/models/Llama-2-7B-GGML/llama-2-7b.ggmlv3.q8_0.bin
```

I'm using WSL2, and I can run pytorch cuda
```python
import torch
torch.cuda.is_available()
# True
```

Do you have any suggestion?
Thank you

**Comment by liltom-eth** [comment]
WSL2 should be fine, I am also using WSL2 for GPU inference on llama2 or gptq models.
gptq model loads much faster.

**Comment by blackhawkee** [comment]
thanks @liltom-eth , @smithlai. able to run on cpu and wsl2 as per above.

**Comment by liltom-eth** [comment]
@blackhawkee @smithlai welcome contributing your benchmark performance [here](https://github.com/liltom-eth/llama2-webui#benchmark).
