### ISSUE TITLE
Enable share on gradio?

### ISSUE THREAD

**Issue by jlb1504** [liltom-eth/llama2-webui#2]
Is there a way to enable sharing on gradio when launching the app?  Apologies if this is a newbie question.  Thanks.

**Comment by liltom-eth** [comment]
@jlb1504 try `demo.queue(max_size=20).launch(share=True)` on [this line](https://github.com/liltom-eth/llama2-webui/blob/e30c335b3efaa121803312994fc5781848413dfa/app.py#L322), I haven't got a chance to try that.

**Comment by jlb1504** [comment]
Yes, this works just as expected.  Thanks!
