### ISSUE TITLE
[FEATURE] Is there any way to expose this as Rest API instead of Default UI

### ISSUE THREAD

**Issue by ajasingh** [liltom-eth/llama2-webui#27]
Is there any way where this could be exposed as Rest API instead of a WebUI default

**Comment by liltom-eth** [comment]
Yeah. A REST API should be helpful to be served as a backend for other AI applications. 
Still working on that.

**Comment by ruizcrp** [comment]
This feature would be great! Is there still development on it?

**Comment by liltom-eth** [comment]
@ruizcrp This feature has already been implemented. Check the doc [here](https://github.com/liltom-eth/llama2-webui#start-openai-compatible-api).

**Comment by ruizcrp** [comment]
Hi, thanks for the answer. I saw that but thought that both cannot run at the same time. E.g. two different processes that would require double the RAM if they are running at the same time and could not share a common queue. But maybe that's not the case?

**Comment by liltom-eth** [comment]
@ruizcrp Yeah, thanks for letting me know about that use case. The API is implemented later after the UI. Maybe you can try some OpenAI-compatible UI since our API is also OpenAI-compatible.
