### ISSUE TITLE
loading ggmlv3.q4 and q4_K_M

### ISSUE THREAD

**Issue by step21** [liltom-eth/llama2-webui#3]
Hey,

locally both of these work with llama.cpp. I also am approved for llama v2, but don't really want to upload manually or redownload that. However when I try to use the ggml models by the bloke, I always get a verification error.
```
CUDA not found.
Traceback (most recent call last):
  File "/home/user/project/llama2-webui/app.py", line 61, in <module>
    llama2_wrapper.init_tokenizer()
  File "/home/user/project/llama2-webui/model.py", line 21, in init_tokenizer
    self.tokenizer = LLAMA2_WRAPPER.create_llama2_tokenizer(self.config)
  File "/home/user/project/llama2-webui/model.py", line 65, in create_llama2_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/home/user/.local/share/virtualenvs/llama2-webui-NwPLNNNA/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/user/.local/share/virtualenvs/llama2-webui-NwPLNNNA/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/user/.local/share/virtualenvs/llama2-webui-NwPLNNNA/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/user/.local/share/virtualenvs/llama2-webui-NwPLNNNA/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/user/.local/share/virtualenvs/llama2-webui-NwPLNNNA/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/path-to/Llama-2-7b-chat-hf'. Use `repo_type` argument if needed.
```
My models are stored in `models/` (within the llama2-webui folder). I suspect it is some path problem, but I double checked multiple times and also used the full path as well as a partial path, with similar results. Still probably some mistake by me, but would be great if you have any idea.

**Comment by liltom-eth** [comment]
Hi, can you show your `.env` file. `CUDA not found.` means you are trying to load Llama2, gptq models. 
If you are loading ggml models, it should print out like [this ](https://github.com/liltom-eth/llama2-webui/blob/e30c335b3efaa121803312994fc5781848413dfa/app.py#L44).
Make sure you have set `LLAMA_CPP = True` in `.env` file.

**Comment by step21** [comment]
hey, thanks for the quick reply. I used the example for `llama-2-7b-chat.ggmlv3.q4_0.bin`
This is my `.env` file:

```
MODEL_PATH = "/home/user/project/models/llama-2-7b-chat.ggmlv3.q4_0.bin"
LOAD_IN_8BIT = False
LOAD_IN_4BIT = True
LLAMA_CPP = True

MAX_MAX_NEW_TOKENS = 2048
DEFAULT_MAX_NEW_TOKENS = 1024
MAX_INPUT_TOKEN_LENGTH = 4000

DEFAULT_SYSTEM_PROMPT = "\
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.\
"
```

**Comment by step21** [comment]
mmh, I didn't really change anything, mostly reloaded my venv (but which I also did before) and now it says it is running on CPU with llama.cpp. Though now it also does not find the model and seemingly doesn't pick up the path properly from `.env`.

**Comment by step21** [comment]
Now it seems to work. Apparently for a venv, it only picks up changes to the `.env` after exiting the venv/environment and reloading it?

**Comment by liltom-eth** [comment]
It is wired. The '.env' should be loaded every time you run `app.py`.

**Comment by liltom-eth** [comment]
@step21 welcome contributing your benchmark performance [here](https://github.com/liltom-eth/llama2-webui#benchmark).
