### ISSUE TITLE
[FEATURE] add `--iter` argument for benchmark

### ISSUE THREAD

**Issue by liltom-eth** [liltom-eth/llama2-webui#33]
Running the benchmark a couple of times to take the average results, the default can be set as `--iter 1`.

**Comment by jules552** [comment]
Will try to look at it even if I haven't use python in a while, but it seems I have not the rights to assign myself to this issue

**Comment by liltom-eth** [comment]
Thanks. Yeah, only the owners can assign issues. This feature is not difficult in python by using a package like [argparse](https://pymotw.com/2/argparse/).
