### ISSUE TITLE
Error in text generation, major error

### ISSUE THREAD

**Issue by Lyn4ever29** [liltom-eth/llama2-webui#36]
There is a major error as the picture show.
![image](https://github.com/liltom-eth/llama2-webui/assets/25952589/335cd57c-f52d-4301-9320-221d469639a1)

.env is 
`
MODEL_PATH = "/data/model/llama2/Llama-2-13b-chat-hf"
LOAD_IN_8BIT = False
LOAD_IN_4BIT = False
LLAMA_CPP = False

MAX_MAX_NEW_TOKENS = 2048
DEFAULT_MAX_NEW_TOKENS = 1024
MAX_INPUT_TOKEN_LENGTH = 4000

DEFAULT_SYSTEM_PROMPT = "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information."

`

**Comment by liltom-eth** [comment]
@Lyn4ever29 check [this](https://github.com/liltom-eth/llama2-webui/issues/9#issuecomment-1651093448). He has successfully run Llama-2-13b on his device. I believe the model checkpoints have issues.
