### ISSUE TITLE
When I was running app. py, I encountered some errors

### ISSUE THREAD

**Issue by 15899885850** [liltom-eth/llama2-webui#48]
This is my problem, i need help!!

root@autodl-container-66e0119cac-10ae5257:~/autodl-tmp/llama2-webui# python app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from llama2_wrapper import LLAMA2_WRAPPER
  File "/root/autodl-tmp/llama2-webui/llama2_wrapper/__init__.py", line 1, in <module>
    from .model import LLAMA2_WRAPPER, get_prompt
  File "/root/autodl-tmp/llama2-webui/llama2_wrapper/model.py", line 7, in <module>
    class LLAMA2_WRAPPER:
  File "/root/autodl-tmp/llama2-webui/llama2_wrapper/model.py", line 163, in LLAMA2_WRAPPER
    chat_history: list[tuple[str, str]] = [],
TypeError: 'type' object is not subscriptable

**Comment by liltom-eth** [comment]
Hi, can you try re-clone the repo and re-install llama2-wrapper? It shouldn't happen.
And you also can try `python benchmark.py` to test if model is correctly running.

**Comment by 15899885850** [comment]
> Hi, can you try re-clone the repo and re-install llama2-wrapper? It shouldn't happen.嗨，您可以尝试重新克隆存储库并重新安装 llama2 包装器吗？它不应该发生。 And you also can try `python benchmark.py` to test if model is correctly running.您还可以尝试 `python benchmark.py` 测试模型是否正确运行。

Thank you! I have already solved this problem!
