### ISSUE TITLE
Cant seem to run it on GPU

### ISSUE THREAD

**Issue by rishabh-gurbani** [liltom-eth/llama2-webui#50]
im running this on a machine with Nvidia A100 but it doesnt seem to make use of the gpu. 

System Specs :
4x Nvidia A100 80Gb
540 Gigs of ram

Benchmarks :
Initialization time: 0.2208 seconds.
Average generation time over 5 iterations: 31.0348 seconds.
Average speed over 5 iterations: 5.0459 tokens/sec.
Average memory usage during generation: 4435.30 MiB

**Comment by rishabh-gurbani** [comment]
can you help me w this issue?

**Comment by rishabh-gurbani** [comment]
llama-2-7b-chat.ggmlv3.q4_0.bin
running this basic model

**Comment by liltom-eth** [comment]
Hi, you can try running `env_examples/.env.13b_example` or `env_examples/.env.7b_gptq_example` models on A100 GPU. Here is a [colab ](https://github.com/liltom-eth/llama2-webui/blob/main/colab/Llama_2_7b_Chat_GPTQ.ipynb) example runs GPTQ model on T4 GPU with 15.9851 tokens/sec.

**Comment by liltom-eth** [comment]
Do not run ggml models on server because ggml models only runs on CPU (without acceleration), and the server's CPU is super slow.

**Comment by rishabh-gurbani** [comment]
Alright, will try and get back, thanks!
