### ISSUE TITLE
chat too slow!

### ISSUE THREAD

**Issue by Hyingerrr** [liltom-eth/llama2-webui#69]
I am using Collab Pro, running on the GPU, executing the following code to ask a question, and responding for 50 seconds, which is too slow. Is there any way to accelerate?

`prompt = get_prompt("Please help me explain the TCP handshake")

res = llama2_wrapper(prompt)

print(res)`

**Comment by liltom-eth** [comment]
collab runs faster on gptq backend, because its CPU is super slow.


Llama-2-7b-Chat-GPTQ | 4 bit | Google Colab T4 | 5.8 GB VRAM | 18.19 (tokens/sec) 
-- | -- | -- | -- | --
