### ISSUE TITLE
model is not None

### ISSUE THREAD

**Issue by quanpinjie** [liltom-eth/llama2-webui#71]
Running on backend llama.cpp.
Traceback (most recent call last):
  File "/root/llama2-webui/app.py", line 325, in <module>
    main()
  File "/root/llama2-webui/app.py", line 56, in main
    llama2_wrapper = LLAMA2_WRAPPER(
                     ^^^^^^^^^^^^^^^
  File "/root/llama2-webui/llama2_wrapper/model.py", line 99, in __init__
    self.init_model()
  File "/root/llama2-webui/llama2_wrapper/model.py", line 103, in init_model
    self.model = LLAMA2_WRAPPER.create_llama2_model(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/llama2-webui/llama2_wrapper/model.py", line 125, in create_llama2_model
    model = Llama(
            ^^^^^^
  File "/root/llama2-webui/new1/lib/python3.11/site-packages/llama_cpp/llama.py", line 323, in __init__
    assert self.model is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by jamartinh** [comment]
Same here !

**Comment by liltom-eth** [comment]
Thanks for the issue. Might be some issue from llama.cpp. Will have a look.

**Comment by talarari** [comment]
https://stackoverflow.com/questions/76986412/assertionerror-when-using-llama-cpp-python-in-google-colab

need to use llama-cpp-python==0.1.78
the format changed

**Comment by liltom-eth** [comment]
@jamartinh @HyperUpscale Thanks for the feedback. I believe the issue is mainly due to the new GGUF format.
A quick solution is try install from requirements like 
```
git clone https://github.com/liltom-eth/llama2-webui.git
cd llama2-webui
pip install -r requirements.txt
```

**Comment by liltom-eth** [comment]
@jamartinh @HyperUpscale hi now the new release llama2-wrapper=0.1.13 will lock on llama-cpp-python = "0.1.77" to support old ggml models.
New release will support gguf models.

**Comment by liltom-eth** [comment]
#73 now supporting gguf models.

**Comment by liltom-eth** [comment]
#73 now supporting gguf models.
